using System;
using NUlid;

namespace UniversityManagementSystem.Core.Entities
{
    public enum InsightType
    {
        WeaknessDetected        = 0,   // AI found a weak subject
        ImprovementDetected     = 1,   // AI found positive trend
        InactivityAlert         = 2,   // Student inactive for N days
        ExamApproaching         = 3,   // Exam in next 7 days
        AssignmentDeadline      = 4,   // Assignment due soon
        StreakMilestone         = 5,   // Streak achievement
        GoalAchieved            = 6,   // Student reached a goal
        StudyPlanRecommendation = 7,   // New study plan available
        RiskAlert               = 8,   // At-risk academic situation
        WeeklyReport            = 9,   // Weekly progress report
        MonthlyReport           = 10,  // Monthly progress report
        TeachingRecommendation  = 11,  // For doctors
        ClassPerformanceAlert   = 12,  // Doctor: class is struggling
    }

    public enum InsightPriority
    {
        Low     = 0,
        Medium  = 1,
        High    = 2,
        Urgent  = 3,
    }

    /// <summary>
    /// AI-generated insight for a user — drives smart notifications
    /// and the companion's proactive follow-up engine.
    ///
    /// Unlike generic AppNotification, AiInsight carries structured
    /// data (JSON payload) and is generated by the AI background service.
    /// The .NET notification service reads unread insights and converts
    /// them into AppNotifications with AI-personalized message text.
    /// </summary>
    public class AiInsight : BaseEntity
    {
        public Ulid UserId { get; set; }
        public Ulid? AiCompanionProfileId { get; set; }

        public InsightType InsightType { get; set; }
        public InsightPriority Priority { get; set; } = InsightPriority.Medium;

        /// Short human-readable title (AI-generated)
        public string Title { get; set; } = string.Empty;
        /// Full personalized message body (AI-generated, aware of user context)
        public string Message { get; set; } = string.Empty;
        /// JSON payload with structured data (grades, subject names, etc.)
        public string DataPayload { get; set; } = "{}";
        /// Deep link the user should follow to act on this insight
        public string? ActionUrl { get; set; }
        /// Whether the AI notification has been sent to the user
        public bool NotificationSent { get; set; } = false;
        /// Whether the user has acknowledged/dismissed this insight
        public bool IsAcknowledged { get; set; } = false;
        /// When this insight expires / is no longer relevant
        public DateTime? ExpiresAt { get; set; }
        /// Used by the follow-up engine to not re-generate same insight
        public string DeduplicationKey { get; set; } = string.Empty;

        // Navigation
        public SystemUser User { get; set; } = null!;
        public AiCompanionProfile? AiCompanionProfile { get; set; }
    }
}
